CHAMPION_ROLES = {
    "Aatrox": ["Baron", "Jungle"],
    "Ahri": ["Mid"],
    "Akali": ["Mid", "Baron"],
    "Akshan": ["Mid"],
    "Alistar": ["Support"],
    "Ambessa": ["Baron", "Jungle"],
    "Amumu": ["Jungle", "Baron", "Support"],
    "Annie": ["Mid"],
    "Ashe": ["Dragon", "Support"],
    "Aurelion Sol": ["Mid"],
    "Aurora": ["Mid", "Baron"],
    "Bard": ["Support"],
    "Blitzcrank": ["Support"],
    "Brand": ["Mid", "Support"],
    "Braum": ["Support"],
    "Caitlyn": ["Dragon"],
    "Camille": ["Baron", "Jungle"],
    "Corki": ["Dragon", "Mid"],
    "Darius": ["Baron", "Jungle"],
    "Diana": ["Mid", "Jungle", "Baron"],
    "Dr. Mundo": ["Baron", "Jungle"],
    "Draven": ["Dragon"],
    "Ekko": ["Mid", "Jungle", "Baron"],
    "Evelynn": ["Jungle"],
    "Ezreal": ["Dragon"],
    "Fiddlesticks": ["Jungle"],
    "Fiora": ["Baron"],
    "Fizz": ["Mid", "Jungle", "Baron"],
    "Galio": ["Mid", "Support"],
    "Garen": ["Baron"],
    "Gnar": ["Baron"],
    "Gragas": ["Jungle", "Baron"],
    "Graves": ["Jungle", "Baron"],
    "Gwen": ["Baron", "Jungle"],
    "Hecarim": ["Jungle"],
    "Heimerdinger": ["Mid"],
    "Irelia": ["Mid", "Baron"],
    "Janna": ["Support"],
    "Jarvan IV": ["Jungle", "Baron"],
    "Jax": ["Baron", "Jungle"],
    "Jayce": ["Baron", "Mid"],
    "Jhin": ["Dragon"],
    "Jinx": ["Dragon"],
    "Kai'Sa": ["Dragon"],
    "Kalista": ["Dragon"],
    "Karma": ["Support", "Mid"],
    "Kassadin": ["Mid", "Baron"],
    "Katarina": ["Mid"],
    "Kayle": ["Baron", "Mid", "Jungle"],
    "Kayn": ["Jungle"],
    "Kennen": ["Baron", "Mid"],
    "Kha'Zix": ["Jungle"],
    "Kindred": ["Jungle"],
    "Kog'Maw": ["Dragon"],
    "Lee Sin": ["Jungle"],
    "Leona": ["Support"],
    "Lillia": ["Jungle"],
    "Lissandra": ["Mid"],
    "Lucian": ["Dragon", "Mid"],
    "Lulu": ["Support"],
    "Lux": ["Support", "Mid"],
    "Malphite": ["Baron", "Support", "Mid"],
    "Maokai": ["Support", "Baron", "Jungle"],
    "Master Yi": ["Jungle"],
    "Milio": ["Support"],
    "Miss Fortune": ["Dragon"],
    "Mordekaiser": ["Baron", "Jungle"],
    "Morgana": ["Support", "Mid", "Jungle"],
    "Nami": ["Support"],
    "Nasus": ["Baron"],
    "Nautilus": ["Support", "Baron", "Jungle"],
    "Nidalee": ["Jungle", "Baron"],
    "Nilah": ["Jungle", "Dragon"],
    "Nocturne": ["Jungle"],
    "Nunu": ["Jungle"],
    "Olaf": ["Jungle", "Baron"],
    "Orianna": ["Mid"],
    "Ornn": ["Baron"],
    "Pantheon": ["Jungle", "Baron", "Mid"],
    "Poppy": ["Baron", "Jungle"],
    "Pyke": ["Support"],
    "Rakan": ["Support"],
    "Rammus": ["Jungle"],
    "Rell": ["Support"],
    "Renekton": ["Baron"],
    "Rengar": ["Jungle"],
    "Riven": ["Jungle", "Baron"],
    "Rumble": ["Baron"],
    "Ryze": ["Mid"],
    "Samira": ["Dragon"],
    "Senna": ["Support"],
    "Seraphine": ["Support", "Mid"],
    "Sett": ["Baron"],
    "Shen": ["Baron", "Jungle"],
    "Shyvana": ["Jungle"],
    "Singed": ["Baron"],
    "Sion": ["Baron"],
    "Sivir": ["Dragon"],
    "Sona": ["Support"],
    "Soraka": ["Support"],
    "Swain": ["Mid", "Support"],
    "Syndra": ["Mid"],
    "Talon": ["Jungle", "Mid"],
    "Teemo": ["Mid", "Baron"],
    "Thresh": ["Support"],
    "Tristana": ["Dragon"],
    "Tryndamere": ["Jungle", "Baron"],
    "Twisted Fate": ["Mid"],
    "Twitch": ["Dragon", "Jungle"],
    "Urgot": ["Baron"],
    "Varus": ["Dragon"],
    "Vayne": ["Dragon"],
    "Veigar": ["Mid", "Support"],
    "Vel'Koz": ["Mid", "Support"],
    "Vex": ["Mid"],
    "Vi": ["Jungle"],
    "Viego": ["Jungle", "Baron"],
    "Viktor": ["Mid"],
    "Vladimir": ["Mid", "Baron"],
    "Volibear": ["Jungle", "Baron"],
    "Warwick": ["Jungle", "Baron"],
    "Wukong": ["Jungle", "Baron"],
    "Xayah": ["Dragon"],
    "Xin Zhao": ["Jungle"],
    "Yasuo": ["Mid", "Baron"],
    "Yone": ["Mid", "Baron", "Jungle"],
    "Yuumi": ["Support"],
    "Zed": ["Mid", "Jungle", "Baron"],
    "Zeri": ["Dragon"],
    "Ziggs": ["Mid"],
    "Zilean": ["Support"],
    "Zoe": ["Mid"],
    "Zyra": ["Mid", "Support"],
}
